#!/bin/sh
clear
echo
echo
echo
toilet -f future --filter metal:border " Runtime Typing in Python "
echo
sleep 2
toilet -f future --gay " David Mertz, Ph.D. "
echo
sleep 2
toilet -f smblock "~ github : DavidMertz"
echo
toilet -f smblock "~ / PythonRuntimeTyping"
echo
echo
echo
sleep 5

